Party list
cldif/PartyZZ pull request #13
Opened 2021-05-25 08:51 UTC by Vincent0Lourdin

Concerns #5

2021-05-25 09:11 UTC, cldif requested changes

2021-05-25 09:11 UTC, cldif commented on src/Party-functions.js
> +function PartyList(){
Je pense que tu devrais séparer tes deux composants `PartyRender` et `PartyList` en deux fichiers distincts. Même s'ils sont utilisés conjointement, ils sont indépendants.

2021-05-25 09:11 UTC, cldif commented on src/Party-functions.js
> +    const truc = async () => {
Cf mon commentaire ici :
https://github.com/cldif/PartyZZ/pull/13#r638591321

2021-05-25 09:11 UTC, cldif commented on src/Party-functions.js
> +                {state.loading !== true && state.partys !== null ? Object.values(state.partys).map(row => {
```suggestion
                {!state.loading && state.partys !== null ? Object.values(state.partys).map(row => {
```

2021-05-25 09:11 UTC, cldif commented on src/Party.js
> +    }
Changer les `defaultProps` ici voire ne rien mettre du tout.

2021-05-25 09:11 UTC, cldif commented on src/Party.js
> +    }
Inutile de mettre des valeurs initiales.

2021-05-25 09:13 UTC, cldif commented
Ne pas ajouter de fichier https://github.com/cldif/PartyZZ/blob/party-list/public/slip.jpg.

2021-05-25 09:49 UTC, cldif requested changes

2021-05-25 09:49 UTC, cldif commented on src/Party-functions.js
> +                    </Select>
Utiliser un chip ici : https://material-ui.com/components/selects/#multiple-select

2021-05-25 09:49 UTC, cldif commented on src/Party-functions.js
> +                    label="ID de l'hôte"
Mettre le nom de l'hôte plutôt, l'utilisateur ne s'intéresse pas à l'ID. Celui-ci ne nous sert qu'à nous, développeurs

2021-05-25 09:49 UTC, cldif commented on src/Party-functions.js
> +                    label="ID de la fête"
Pas utile non plus : il faudrait plutôt utiliser le nom de la fête.

2021-05-25 09:49 UTC, cldif commented on src/Party-functions.js
> +                        <TableCell>ID fête</TableCell>
Cf :
- https://github.com/cldif/PartyZZ/pull/13#r638631829
- https://github.com/cldif/PartyZZ/pull/13#r638632165

2021-05-25 10:00 UTC, cldif requested changes

2021-05-25 10:00 UTC, cldif commented on src/Party-functions.js
> +                }) : "no data"}
Plutôt mettre un feedback quand on est en train de charger les données : 
https://material-ui.com/components/progress/#circular-indeterminate

2021-05-26 08:35 UTC, Hellyon commented on src/Party-functions.js
> +                <br></br>
Des margin ou des balises de saut de lignes sont de bonnes solutions. Il faut vérifier que l'affichage reste bien en fonction de la taille de l'écran.

2021-05-26 13:43 UTC, Vincent0Lourdin commented on src/Party-functions.js
> +                <br></br>
Les composants passent les uns sous les autres quand on rétrécit la fenêtre en largeur, donc c'est ok. Je clos la conversation.

2021-05-28 09:53 UTC, merged